### ISSUE TITLE
Product Owner/Manager Similarities/Differences?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/product-owner-guide#46]
While listening to Tim Ferriss' latest Podcast featuring **Ben Horowitz** [tim.blog/2019/10/24/ben-horowitz](https://tim.blog/2019/10/24/ben-horowitz)
I was reminded of how **_important_ Product Management** is in the context of a **_product_-focussed startup**.

> I would **_highly_ recommend** people **listen** to the **podcast** (_skip the ads and listen at 1.5x speed_)
as Ben Horowitz is one of the few people in the world who has not only **`done`** the [**hard work**](https://www.amazon.com/Hard-Thing-About-Things-Building/dp/0062273205) of 
starting (building/managing) and selling _several_ seriously successful software product companies, 
he has made the time to write about it extensively so that others can learn his lessons _much_ faster. 

In the podcast Tim asks Ben about his famous blog post **_Good_ Product Manager/_Bad_ Product Manager**: https://a16z.com/2012/06/15/good-product-managerbad-product-manager [5 min read]

A few highlights from the post:
+ Good product managers **_know_ the market**, the product, the product line and the **competition extremely well** and **operate** from a strong basis of **knowledge** and ***confidence***.
+ A good product manager is the CEO of the product.
+ Good product managers **communicate crisply** to engineering in writing as well as verbally. Good product managers **don’t give direction _informally_**.
+ Bad product managers have lots of excuses. [_Never make excuses..._](https://github.com/dwyl/quotes/pull/9)
+ Good product managers focus the team on revenue and customers. Bad product managers focus team on how many features Microsoft is building.
+ Good product managers think in terms of delivering superior value to the market place during inbound planning and achieving market share and revenue goals during outbound. Bad product managers get very confused about the differences amongst delivering value, matching competitive features, pricing, and ubiquity. Good product managers decompose problems. Bad product managers combine all problems into one.
+ Good product managers think about the **story** they want written by the press. 
+ Good product managers ***anticipate*** the serious **product flaws** and **build** real **solutions**. Bad product managers **put out fires** all day. Good product managers **take _written_ positions** on important issues.

> 🥚**Easter Egg**: Ben's commencement address at Columbia University [youtu.be/WRYRBGX4lVM](https://youtu.be/WRYRBGX4lVM)
on figuring out what to do with your life, was referenced in our super popular [email sending tutorial](https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/tree/d0750f82dd4c56372631fd413d41b1ce7b297afe#16-re-test-submitting-the-form) ... if you didn't think to watch it while reading the tutorial at the time, watch it now 
(_add it to your list to watch in your next pomodoro break_)! 🍅
It's worth your time. Gist: "_**Do NOT follow** your **passion**, **follow** your **contribution**._" 💡 
"***You will be the generation that unlocked human potential.***" [16:39](https://youtu.be/WRYRBGX4lVM?t=982)

> _**Side Note**: **really** looking forward to read Ben's new book_
"What You Do Is Who You Are: How to Create Your Business Culture"
https://www.amazon.com/What-You-Do-Who-Are/dp/B07Q4S712S
(_considering getting it on Audible ..._) 📘 🎧 💭 

# Todo

+ [ ] Research and write up the difference between the **Product _Owner_** and **Product _Manager_** Role. 
  + [ ] @iteles to decide where the content should go. 
  (_i.e. should it be a **section** of **`this` repo** or a distinct **`new`** one on Product Management? Can/should we use it as opportunity to start our "blog"...?_)
+ [ ] Which ***Metrics*** should the Product Manager **focus** on (_**When** and **Why**_) ?
  e.g: the Product Manager could focus on **Growth** in **Revenue** from **_paying_ customers**. 
  Or **number of _referrals_** (_people who started using the product because a friend referred them_)
  But these metrics are "lagging" because it can only be the focus once **customer _satisfaction_** and **product market fit** are achieved. 
+ [ ] How should the Product Manger's **performance** be ***measured***?
  + [ ] Consequently, should the Product Manager's [bonus] compensation be linked to the metric? 💭 
+ [ ] If your team/company only has the budget for _one_ of the roles which should it be?
  ***or*** if the person on your team has the ability to do _both_ roles how should they split their time? 
e.g: 60% Product Ownership / 40% Product Management
  + [ ] Which role has more impact at the various stages of the product lifecycle?
  e.g: the Product Manager might be responsible for researching competitors developing the overall "strategy" ***`before`*** a Product Owner is needed to flesh out the details of the product features ... 
+ [ ] List the **best resources** available for learning how to become an **_excellent_ Product Manager**:
  + [ ] Books?
  + [ ] Blog posts (_written by people who are **doing** the work_)
  + [ ] Online courses free/paid?
  + [ ] Videos? (_share links! and include a brief summary of the "key takeaways"_)

If you are keen to help us research and write this up, please communicate your interest by commenting! 
We are very happy to pay you for your time (_e.g: in Amazon Vouchers if you're a first-time contributor or **invoice** us if you have already/previously worked with us!_) 
As always [**estimate**](https://github.com/dwyl/contributing/tree/d19e3fbb4deae9c46dc64f7e58ec99d95dbb3ac6#step-1-estimate-the-time-required-to-perform-the-work) the expected time required **`before`** starting the task!

**Comment by nelsonic** [comment]
What Are the Basics of a Product Manager Role by Google PM
[![image](https://user-images.githubusercontent.com/194400/67756455-f444c580-fa31-11e9-912f-ab65ffd1ea5a.png)](https://youtu.be/ntzB9pGsD3E)

20 Years of Product Management in 25 Minutes by Dave Wascha
[![image](https://user-images.githubusercontent.com/194400/67756601-3110bc80-fa32-11e9-9e46-c449a9810abb.png)](https://youtu.be/i69U0lvi89c)
https://youtu.be/i69U0lvi89c

**Comment by nelsonic** [comment]
https://youtu.be/huTSPanUlQM

**Comment by nelsonic** [comment]
Top 75+ Resources for Product Managers: https://www.sachinrekhi.com/top-resources-for-product-managers

**Comment by nelsonic** [comment]
https://blog.pragmaticengineer.com/the-product-minded-engineer/
https://news.ycombinator.com/item?id=21732027

**Comment by nelsonic** [comment]
And then the Pandemic Hit and all "This Week" priorities were obliterated. 
@iteles do you think you will have time to pick this up? 
or can we assign it to @Shamus-88 ?

**Comment by seaneady** [comment]
I'm more than happy to jump in here and carry on the research. Would that be in the form of a new issue/thread? Or just continuing on this one?

**Comment by nelsonic** [comment]
@seaneady please add more to this issue. But ultimately we’re going to create a .md file here on GitHub and then publish it as a “blog” post.
